# Default values for mutating-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

annotations:
  cert-manager.io/inject-ca-from: mutating/mutating-webhook-ca

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "mutating-webhook.acme.com"

image:
  repository: docker.io/jinqin2003/mutating-webhook
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# We only need to check every 30s since harbor webhook is not a high-throughput service.
livenessProbe:
  enabled: true
  periodSeconds: 30
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP
readinessProbe:
  enabled: false
  periodSeconds: 30
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP

service:
  type: ClusterIP
  port: 443

podTemplate:
  annotations:
    sidecar.istio.io/inject: "false"

configmap:
  tlsEnabled: "true"
  logLevel: "trace"
  logAsJSON: "true"
  sourceRegistry: "docker.fake.io"
  targetRegistry: "docker.io"
