# Default values for mutating-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

annotations:
  cert-manager.io/inject-ca-from: harbor/mutating-webhook-ca

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "mutating-webhook.jinqin2003.io"

image:
  repository: docker.io/jinqin2003/mutating-webhook
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# We only need to check every 30s since harbor webhook is not a high-throughput service.
livenessProbe:
  enabled: true
  periodSeconds: 30
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP
readinessProbe:
  enabled: false
  periodSeconds: 30
  initialDelaySeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  scheme: HTTP

service:
  type: ClusterIP
  port: 443

podTemplate:
  annotations:
    sidecar.istio.io/inject: "false"

configmap:
  tlsEnabled: "true"
  logLevel: "trace"
  logAsJSON: "true"
  sourceRegistry: "docker.jinqin2003.us"
  targetRegistry: "docker.io"

# tagging -- These values are mapped to labels based off of the [Cloud Resource Tagging Policy](https://docs.google.com/document/d/1DiR8zmcQJocltuQEzRQhl6d37W3NnxGwaPa1vbo38M0/edit)
tagging:
  finance:
    # tagging.finance.class -- This values are mapped to labels based off of the [Cloud Resource Tagging Policy](https://docs.google.com/document/d/1DiR8zmcQJocltuQEzRQhl6d37W3NnxGwaPa1vbo38M0/edit)
    class: non-revenue
    # tagging.finance.class -- This values are mapped to labels based off of the [Cloud Resource Tagging Policy](https://docs.google.com/document/d/1DiR8zmcQJocltuQEzRQhl6d37W3NnxGwaPa1vbo38M0/edit)
    costcenter: ~
  ownership:
    # tagging.ownership.team -- This values are mapped to labels based off of the [Cloud Resource Tagging Policy](https://docs.google.com/document/d/1DiR8zmcQJocltuQEzRQhl6d37W3NnxGwaPa1vbo38M0/edit)
    team: engineering.sre
  operations:
    environmentLevel: "lab"
  security:
    dataConfidentiality: "internal"
    exposure: "private"
