apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  namespace: apps
spec:
  restartPolicy: Always
  containers:
    - name: alpine-test-1
      image: docker.fake.io/alpine:latest
      args:
        - sleep
        - "60"
