apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: docker.cogitocorp.us/nginx:1.21
      name: test-nginx
  restartPolicy: Always
