apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "harbor-proxy-webhook.name" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "harbor-proxy-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: {{ template "harbor-proxy-webhook.fullname" . }}
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "harbor-proxy-webhook.name" . }}
        path: /mutate-pods
        port: {{ .Values.service.port }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
