apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: {{ template "harbor-proxy-webhook.name" . }}
  name: {{ template "harbor-proxy-webhook.name" . }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "harbor-proxy-webhook.name" . }}-ca
  dnsNames:
    - {{ template "harbor-proxy-webhook.name" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: selfsigned-issuer
