apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "harbor-proxy-webhook.name" . }}
  name: {{ include "harbor-proxy-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.configmap }}
  tlsEnabled: {{ .tlsEnabled | quote }}
  logLevel: {{ .logLevel | quote }}
  logAsJSON: {{ .logAsJSON | quote }}
  harborRegistry: {{ .harborRegistry }}
  {{- end }}
