apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "mutating-webhook.name" . }}
  name: {{ include "mutating-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.configmap }}
  tlsEnabled: {{ .tlsEnabled | quote }}
  logLevel: {{ .logLevel | quote }}
  logAsJSON: {{ .logAsJSON | quote }}
  sourceRegistry: {{ .sourceRegistry | quote }}
  targetRegistry: {{ .targetRegistry | quote }}
  {{- end }}
