apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: {{ template "mutating-webhook.name" . }}
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
